In [1]:
import numpy as np

In [59]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [37]:
print(a+b)

[5 7 9]


In [38]:
print(a-b)

[-3 -3 -3]


In [39]:
print(a*b)

[ 4 10 18]


In [40]:
print(a/b)

[0.25 0.4  0.5 ]


In [41]:
print(a**3)

[ 1  8 27]


In [42]:
print(np.sqrt(a)) #to find the sq root

[1.         1.41421356 1.73205081]


In [43]:
print(np.power(a,5)) #for n exponent

[  1  32 243]


In [44]:
arr = np.array([10,20,20,30,40,50]) # define 1d array

In [20]:
print(np.mean(arr)) # to find the average

28.333333333333332


In [21]:
print(np.median(arr)) # to find mid value

25.0


In [22]:
print(np.max(arr)) # highest value

50


In [23]:
print(np.min(arr)) # lowest value

10


In [24]:
print(np.sum(arr)) # sum of element

170


In [25]:
print(np.std(arr)) #standard deviation

13.43709624716425


In [26]:
print(np.var(arr))

180.55555555555557


In [32]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [33]:
arr = np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]


In [35]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [49]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.ones((2,4,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [51]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
np.arange(1,11) #array in particular range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
np.random.rand(5) #given random numbers below 1

array([0.22343748, 0.38285002, 0.14996703, 0.1656626 , 0.60794147])

In [48]:
np.random.randint(1,100,10) #give random integers

array([14, 69, 40, 69, 78, 47, 86, 45, 43, 41])

In [52]:
arr = np.array([5,2,9,1])
print(np.sort(arr))

[1 2 5 9]


In [56]:
arr = np.array([1,2,2,3,3,4])
print(np.unique(arr))

[1 2 3 4]


In [63]:
arr = np.array([1,2,3,4,5,6])
print(np.split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([10,20,30,40,50])
